version: "3.8"

services:
  backend:
    build: ./backend
    command: "sleep infinity"
    volumes: 
      - ./:/workspace
    
  frontend:
    build: ./frontend
    command: "sleep infinity"
    volumes:
      - ./:/workspace
      - /workspace/frontend/node_modules
    ports:
      - "4200:4200"