version: "3.8"

services:
  messaging:
    build:
      context: .
      dockerfile: messaging.dockerfile
    working_dir: /ap
    volumes: 
      - ./src/:/ap
    environment:
      DOTNET_EnableDiagnostics: 0

  portal:
    build: 
      context: .
      dockerfile: portal.dockerfile
    working_dir: /portal
    volumes:
      - ./AP.Portal/:/portal
    ports:
      - "4200:4200"