version: "3.8"

services:
  backend:
    build: ./backend
    command: "sleep infinity"
    volumes: 
      - ./:/workspace
    depends_on:
      - rabbitmq
      - jaeger
    
  frontend:
    build: ./frontend
    command: "sleep infinity"
    volumes:
      - ./:/workspace
      - /workspace/frontend/node_modules
    ports:
      - "4200:4200"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
      
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"